-- This is just a helper query to verify tournament deletion
-- Not needed for the fix, but useful for debugging

-- Check if a tournament exists (replace with actual tournament ID)
-- SELECT id, name, status FROM tournaments WHERE id = 'your-tournament-id-here';

-- Check for orphaned records (tournament deleted but related records still exist)
-- SELECT 'tournament_public_registrations' as table_name, COUNT(*) as count 
-- FROM tournament_public_registrations tr
-- LEFT JOIN tournaments t ON tr.tournament_id = t.id
-- WHERE t.id IS NULL
-- UNION ALL
-- SELECT 'tournament_registrations', COUNT(*) 
-- FROM tournament_registrations tr
-- LEFT JOIN tournaments t ON tr.tournament_id = t.id
-- WHERE t.id IS NULL
-- UNION ALL
-- SELECT 'tournament_winner_images', COUNT(*) 
-- FROM tournament_winner_images twi
-- LEFT JOIN tournaments t ON twi.tournament_id = t.id
-- WHERE t.id IS NULL
-- UNION ALL
-- SELECT 'tournament_history', COUNT(*) 
-- FROM tournament_history th
-- LEFT JOIN tournaments t ON th.tournament_id = t.id
-- WHERE t.id IS NULL
-- UNION ALL
-- SELECT 'tournament_winners', COUNT(*) 
-- FROM tournament_winners tw
-- LEFT JOIN tournaments t ON tw.tournament_id = t.id
-- WHERE t.id IS NULL;

